### ISSUE TITLE
No support on .jpeg format image

### ISSUE THREAD

**Issue by TrickyShakil** [Piasy/BigImageViewer#163] opened 2019-07-26 06:14 UTC
I have met an issue that .jpeg image is not showing. Is there a known issue? or just no support on .jpeg?

**Comment by Piasy** [comment] 2019-07-26 07:19
Please provide the url or image, and you can also debug with the demo.

**Comment by TrickyShakil** [comment] 2019-07-26 09:08
Here is the image url 
http://www.aitvet.edu.bd/wp-content/uploads/2019/06/received_343050553037353.jpeg

**Comment by Piasy** [comment] 2019-09-17 01:16
It works fine in my device, is it caused by non HTTPS url?

**Comment by TrickyShakil** [comment] 2019-09-17 03:37
No.i tried with firebase storage too.but doesn't work for me.

**Comment by Piasy** [comment] 2019-10-25 10:56
Closing it now, feel free to reopen it if necessary.

**Closed by Piasy** 2019-10-25 10:56 UTC
